version: "3"
services:
    elm:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ".:/usr/src/app"
            - "/usr/src/app/node_modules"
        ports:
            - '3000:3000'
